all:
	latex xbc-spec.tex
	latex xbc-spec.tex
	dvipdf xbc-spec.dvi

clean:
	rm -rf *.acn *.alg *.glg *.glo *.gls *.glsdefs *.ist *.xdy *.acr *.bbl *.blg *.aux *.dvi *.log *.lot *.idx *.toc *.lof *.brf *.out *.pdf

